#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 21 11:06:01 2021

@author: ali
"""

import numpy as np

base_dir = './data/TBX11K/lists/'

lists = ["TBX11K_val.txt","TBX11K_train.txt","TBX11K_trainval.txt"]
lists_out = ["TBX11K_val_imagenet.txt","TBX11K_train_imagenet.txt","TBX11K_trainval_imagenet.txt"]
TBX11K_val = np.loadtxt(base_dir+lists[0],dtype='U20')
TBX11K_train = np.loadtxt(base_dir+lists[1],dtype='U20')
TBX11K_trainval = np.loadtxt(base_dir+lists[2],dtype='U20')

dfs = [TBX11K_val,TBX11K_train, TBX11K_trainval]

for df in range(len(dfs)):
    for i in range(len(dfs[df])):
        
        if dfs[df][i][0]=="h":
            dfs[df][i] = dfs[df][i]+" 0"
        
        elif dfs[df][i][0]=="s":
            dfs[df][i] = dfs[df][i]+" 1"
        
        else:
            dfs[df][i] = dfs[df][i]+" 2"
    
    np.savetxt(fname=base_dir+lists_out[df],X=dfs[df], fmt='%s')